# Generated by Django 2.1.7 on 2019-04-22 22:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='incomeDate',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
    ]
