# Generated by Django 2.1.7 on 2019-04-22 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0003_auto_20190422_2222'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='category',
            field=models.CharField(choices=[('Salary', 'salary'), ('Bonus', 'bonus'), ('Something else', 'something else')], default='Salary', max_length=7),
        ),
    ]
