# Generated by Django 2.1.7 on 2019-04-22 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0005_auto_20190422_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='category',
            field=models.CharField(blank=True, choices=[('salary', 'Salary'), ('bonus', 'Bonus'), ('something else', 'Something else')], default='Salary', max_length=7),
        ),
    ]
