# Generated by Django 2.1.7 on 2019-04-22 22:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0007_auto_20190422_2232'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='comments',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='income',
            name='date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
